name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read    # ler o repo
  pages: write      # gravar no Pages
  id-token: write   # para autenticidade

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .     # publica todo o conteúdo da raiz

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
