name: Build & Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read   # ler o repositório
  pages: write     # gravar no Pages
  id-token: write  # exigido pelo deploy-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build site with Jekyll (Docker)
        run: |
          docker run \
            -v ${{ github.workspace }}:/srv/jekyll \
            -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
            jekyll/builder:latest \
            /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
